/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Package1;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Samsung
 */
public class Issue_book extends javax.swing.JFrame {

    String z;
    /**
     * Creates new form Issuing_a_book
     */
    public Issue_book(String o) {
        z=o;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Report :");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Issue a book");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Issue a Book");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(170, 10, 170, 60);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 60, 490, 20);

        jButton1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton1.setText("View Book Records");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(250, 120, 210, 60);

        jList1.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jList1.setModel(new DefaultListModel());
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 120, 220, 340);

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Library Card Number :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 70, 230, 40);

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(250, 70, 210, 40);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package1/home 1.png"))); // NOI18N
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(20, 470, 110, 100);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Generate Report ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(250, 470, 210, 70);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(250, 190, 210, 270);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package1/person-sitting-on-book-shelf-in-library.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-290, -60, 800, 910);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultListModel m=(DefaultListModel)(jList1.getModel());
m.clear();
jTextArea1.setText("");
    try{
    Class.forName("java.sql.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/library","root","mysql");
    Statement stmt=con.createStatement();
    Statement stmt1=con.createStatement();
    String s="select accession_number from book_information";
    ResultSet rs=stmt.executeQuery(s);
    ResultSet rs1=stmt1.executeQuery(s);
    rs1.first();
    String k=rs1.getString(1);
    while(rs.next())
    {
       String a=rs.getString(1);
       if(a.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"No records to display");
            break;
        }
       m.addElement(a);
    }
       stmt.close();
    con.close();
    }
    catch(Exception e)
    {
        if(e.getMessage().equals("Illegal operation on empty result set."))
        {
            JOptionPane.showMessageDialog(this,"No records to display");
            
        }
        else
        JOptionPane.showMessageDialog(this,e.getMessage());
    }
       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
int count=1;
        if(jTextField1.getText().equals(""))
{
    JOptionPane.showMessageDialog(this,"Library Card Number Needed");
    int s=JOptionPane.showConfirmDialog(this,"Are you registered?","Confirming Registration",JOptionPane.YES_NO_OPTION);
    if(s==1)
    {
        JOptionPane.showMessageDialog(this,"Opening Registration.....");
        New_Registration_form ob=new  New_Registration_form();
        ob.setVisible(true);
        this.dispose();
    }
    else
    {
        DefaultListModel m=(DefaultListModel)(jList1.getModel());
m.clear();
    }
}
        else if(jTextField1.getText()!="mysql")
        {     if(jList1.getSelectedValue()==null)
            {
                JOptionPane.showMessageDialog(this,"No Record Selected");
            }
        else
        {
    int count1=0;
        String Lib=jTextField1.getText();
        try{
    Class.forName("java.sql.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/library","root","mysql");
    Statement stmt=con.createStatement();
    Statement stmtks=con.createStatement();
    String s="select LibraryCard_Number from Registered_issuers";
    ResultSet rs=stmt.executeQuery(s);
    ResultSet rs12=stmtks.executeQuery(s);
    rs12.first();
    String kk=rs12.getString(1);
    while(rs.next())
    {
        String a1=rs.getString(1);
        if(Lib.equals(a1))
        {
        JOptionPane.showMessageDialog(this,"Registration Confirmed");  
count1=2;
break;
        }
        else{
            count1 =1;
            continue;
        }
    }
    if(count1==1)
    {
        JOptionPane.showMessageDialog(this,"Not Registered");
        jTextField1.setText("");
        DefaultListModel m=(DefaultListModel)(jList1.getModel());
        m.clear();
        int sk=JOptionPane.showConfirmDialog(this,"Would you like to register?","Confirming Registration",JOptionPane.YES_NO_OPTION);
    if(sk==0)
    {
        New_Registration_form ob=new  New_Registration_form();
        ob.setVisible(true);
        this.dispose();
        this.setEnabled(false);
    }
    }
    if(count1==2)
    {
       String k=jTextField1.getText();
    Object k1=jList1.getSelectedValue();
    try{
    Class.forName("java.sql.Driver");
    Connection con1=DriverManager.getConnection("jdbc:mysql://localhost/library","root","mysql");
    Statement stmt1=con1.createStatement();
    String skk="insert into Transaction_records(LibraryCard_Number,Accession_Number,Date_of_Issue) values('"+k+"','"+k1+"',curdate());";
    String s1="select Record_Number from transaction_Records";
    int l=stmt.executeUpdate(skk);
    if(l==1)
    {
       JOptionPane.showMessageDialog(this,"Transaction Complete");
       count=0;
    }
    if(count==0)
    {
        try{
    Class.forName("java.sql.Driver");
    Connection conk=DriverManager.getConnection("jdbc:mysql://localhost/library","root","mysql");
    Statement stmtk=conk.createStatement();
    String sql="update book_information set stock_available = 0 where Accession_number = '"+k1+"';";
    stmtk.executeUpdate(sql);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }
    ResultSet rs1=stmt1.executeQuery(s1);
    int ka=0;
    int counter=0;
    while(rs1.next())
    {
    counter++;
    }
    ka=counter;
    JOptionPane.showMessageDialog(this,"Transaction Number: "+ka);
jTextArea1.setText("");
jTextArea1.append("~ ~ ~ ~ Transaction Record ~ ~ ~ ~\n\n");
jTextArea1.append("Library Card Number: "+k+"\n");
jTextArea1.append("Book Issued: "+k1+"\n");
jTextArea1.append("Transaction Number: "+ka+"\n");
}
       
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(this,e.getMessage());
    }
} 
    }
catch(Exception e1)
{
     if(e1.getMessage().equals("Illegal operation on empty result set."))
        {
            JOptionPane.showMessageDialog(this,"Library Card not registered");
            jTextField1.setText("");
            DefaultListModel m=(DefaultListModel)(jList1.getModel());
            m.clear(); 
            int sk=JOptionPane.showConfirmDialog(this,"Would you like to register?","Confirming Registration",JOptionPane.YES_NO_OPTION);
    if(sk==0)
    {
        New_Registration_form ob=new  New_Registration_form();
        ob.setVisible(true);
        this.dispose();
        this.setEnabled(false);
    }
 
        }
     else
    JOptionPane.showMessageDialog(this, e1.getMessage());
}
        }
}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
Front_Page k=new Front_Page();
k.playSound();
Front_Page ob= new Front_Page();
  ob.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked

        if(jList1.getSelectedValue()==null)
        {
            JOptionPane.showMessageDialog(this,"No Record Present");
        }
        try{
    Class.forName("java.sql.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/library","root","mysql");
    Statement stmt=con.createStatement();
    Statement stmtk=con.createStatement();
    Object a1=jList1.getSelectedValue();
    String sql="select stock_available from book_information where accession_number= '"+a1+"';";
    ResultSet rsk=stmtk.executeQuery(sql);
    rsk.first();
    String s1="select * from disposed;";
    ResultSet rs1=stmt.executeQuery(s1);
    String a=rsk.getString(1);
    if(a.equals("0"))
    {
        JOptionPane.showMessageDialog(this,"The book has already been issued");
        jTextField1.setText("");
        DefaultListModel m=(DefaultListModel)(jList1.getModel());
        m.clear();
        int sk=JOptionPane.showConfirmDialog(this,"Wish to see who has issued it?","Question",JOptionPane.YES_NO_OPTION);
    if(sk==0)
    {
        Records_archives ob=new  Records_archives();
        ob.setVisible(true);
        this.dispose();
        this.setEnabled(false);
    }
    else
    {
        jButton2.setEnabled(false);
    }
    }
    int count=0;
    while(rs1.next())
    {if(a1.equals(rs1.getString(1)))
    {
        count=1;
        break;
    }
    }
    if(count==1)
    {
        JOptionPane.showMessageDialog(this,"These records have been disposed");
        jButton2.setEnabled(false);
    }
    else
    {
        jButton2.setEnabled(true);
    }
    stmt.close();
    con.close();
}
catch(Exception e)
{
    if(jList1.getSelectedValue()==null)
{
    JOptionPane.showMessageDialog(this,"No book Selected");
}
    else
    {
    JOptionPane.showMessageDialog(this,e.getMessage());
}
}// TODO add your handling code here:
    }//GEN-LAST:event_jList1MouseClicked

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
  String s=jTextField1.getText();
  try{
    Class.forName("java.sql.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/library","root","mysql");
    Statement stmt=con.createStatement();
    String s1="select * from disposed;";
    ResultSet rs1=stmt.executeQuery(s1);
    int count=0;
    while(rs1.next())
    {if(s.equals(rs1.getString(2)))
    {
        count=1;
        break;
    }
    }
    if(count==1)
    {
        JOptionPane.showMessageDialog(this,"The Issuer records have been disposed");
        jTextField1.setText("");
        DefaultListModel m=(DefaultListModel)(jList1.getModel());
        m.clear();
    }
    stmt.close();
    con.close();
  }
catch(Exception e)
{
JOptionPane.showMessageDialog(this,e.getMessage());
}      // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
DefaultListModel m=(DefaultListModel)(jList1.getModel());
        m.clear();
        jTextArea1.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_jTextField1FocusGained

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
jTextField1.setText(z);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Issue_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Issue_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Issue_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Issue_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String y="";
                new Issue_book(y).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
