/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Package1;


import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;

import javax.swing.JOptionPane;


/**
 *
 * @author Samsung
 */
public class Login_page extends javax.swing.JFrame {
    /**
     * Creates new form Front_Page
     */
    public Login_page() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        jPanel1.setLayout(null);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(150, 110, 230, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Admin Login");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(100, 20, 250, 60);

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("User ID :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 100, 90, 60);

        jPasswordField1.setEchoChar('\u2022');
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(150, 170, 230, 40);

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 160, 90, 60);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(150, 260, 190, 70);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 80, 450, 10);

        jButton2.setFont(new java.awt.Font("Cambria", 1, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Forgot My Password");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(120, 210, 180, 40);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Not Yet Registered?");
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(120, 330, 180, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package1/img-man-reading.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 20, 430, 410);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package1/tumblr_static_dark_wood.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 450, 390);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Front_Page k=new Front_Page();
k.playSound();
String name,pass;
int count=0;
name=jTextField1.getText();
pass=jPasswordField1.getText();
if(name==null||pass==null)
{
    JOptionPane.showMessageDialog(this,"Please enter the required information");
}
else
{
        try{
    Class.forName("java.sql.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/library","root","mysql");
    Statement stmt=con.createStatement();
    String s="select userID,password,Name from user_id";
    ResultSet rs=stmt.executeQuery(s);
    rs.first();
    String a=rs.getString(1);
        String b=rs.getString(2);
        String c=rs.getString(3);
        if((name.equals(a))&&(pass.equals(b)))
        {
        JOptionPane.showMessageDialog(this,"Registration Confirmed");
         JOptionPane.showMessageDialog(this,"Your Administrator code is \n"
            + "KS Codes");
Front_Page ob=new Front_Page();
ob.setVisible(true);
ob.setTitle("Librarian Incharge : "+c);
this.dispose();
this.setEnabled(false);
count=2;
        }
        if(count!=2)
        {
    while(rs.next())
    {
        String a1=rs.getString(1);
        String b1=rs.getString(2);
        if((name.equals(a1))&&(pass.equals(b1)))
        {
            String c1=rs.getString(3);
        JOptionPane.showMessageDialog(this,"Registration Confirmed");
        JOptionPane.showMessageDialog(this,"Your Administrator code is \n"
            + "KS Codes");
        Front_Page ob=new Front_Page();
ob.setVisible(true);
ob.setTitle("Librarian Incharge : "+c1);
this.dispose();
this.setEnabled(false);
count=0;
break;
        }
        else{
            count =1;
            continue;
        }
    }
    if(count==1)
    {
        JOptionPane.showMessageDialog(this,"Not Registered");
        jTextField1.setText("");
        jPasswordField1.setText("");
    }
                
        }
        stmt.close();
    con.close();
}
catch(Exception e)
{
   if(e.getMessage().equals("Illegal operation on empty result set."))
    {
        JOptionPane.showMessageDialog(this,"Not registered");
        jTextField1.setText("");
        jPasswordField1.setText("");
    }
    else
    JOptionPane.showMessageDialog(this,e.getMessage());
}
}    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
   Sign_In_Form ob=new Sign_In_Form();
ob.setVisible(true);
this.dispose();     // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String a=jTextField1.getText();
try
{
    Class.forName("java.sql.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/library","root","mysql");
    Statement stmt=con.createStatement();
    String sql="select Question,Answer,Password,Name from User_id where UserID = '"+a+"';";
    ResultSet rs=stmt.executeQuery(sql);
    rs.first();
    String s1=rs.getString(1);
    String s=JOptionPane.showInputDialog(this,s1);
    String b=rs.getString(2);
    String m=rs.getString(4);
    s.toLowerCase();
    b.toLowerCase();
    if(s.equals(b)==true)
    {
        String c=rs.getString(3);
        JOptionPane.showMessageDialog(this,"Your Password Is : \n"+c);
        Front_Page ob=new Front_Page();
ob.setVisible(true);
ob.setTitle("Librarian Incharge : "+m);
this.dispose();
this.setEnabled(false);
    }
    else
    {
        JOptionPane.showMessageDialog(this,"Wrong answer");
        Login_page ob=new Login_page();
        ob.setVisible(true);
        this.dispose();
    }
    stmt.close();
    con.close();
}
catch(Exception e)
{
    if(e.getMessage().equals("Illegal operation on empty result set."))
    {
        JOptionPane.showMessageDialog(this,"Please enter valid username");
        
        jTextField1.setText("");
        jPasswordField1.setText("");
    }
    else
    JOptionPane.showMessageDialog(this,e.getMessage());
}

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_page().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
