/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Package1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Samsung
 */
public class Records_archives extends javax.swing.JFrame {

    /**
     * Creates new form Records_archives
     */
    public Records_archives() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Records Archives");

        jPanel1.setLayout(null);
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 260, 530, 20);

        jTable1.setBackground(new java.awt.Color(255, 255, 204));
        jTable1.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SNo. ", "Library Card No.", "Accession No.", "Issue date", "Return Date", "Duration", "Fine"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(0).setHeaderValue("SNo. ");
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Library Card No.");
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(90);
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Accession No.");
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(75);
            jTable1.getColumnModel().getColumn(3).setHeaderValue("Issue date");
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(4).setHeaderValue("Return Date");
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(55);
            jTable1.getColumnModel().getColumn(5).setHeaderValue("Duration");
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(6).setHeaderValue("Fine");
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 80, 530, 180);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 80, 550, 190);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Record Archives");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 10, 400, 50);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 60, 570, 20);

        jTextField1.setEditable(false);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(150, 280, 240, 40);

        jTextField2.setEditable(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(150, 330, 240, 40);

        jTextField3.setEditable(false);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(150, 380, 240, 40);

        jTextField4.setEditable(false);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(150, 430, 240, 40);

        jTextField5.setEditable(false);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(150, 480, 240, 40);

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name of Visitor:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 280, 170, 40);

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Phone Number :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 330, 190, 40);

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Title of book :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 380, 190, 40);

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Date of issue :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 430, 220, 40);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package1/home 1.png"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(420, 390, 110, 110);

        jButton1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton1.setText("View Records");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(400, 280, 150, 60);

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Number Of Visits :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 480, 120, 50);
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 260, 530, 270);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package1/new-york-public-library.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-180, -10, 840, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Front_Page k = new Front_Page();
        k.playSound();
        Front_Page ob = new Front_Page();
        ob.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel m = (DefaultTableModel) jTable1.getModel();
        int a = m.getRowCount();
        if (a >= 0) {
            for (int i = 0; i < a; i++) {
                m.removeRow(0);
            }
        }
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/library", "root","mysql");
            Statement stmt = con.createStatement();
            String s = "select Record_Number,LibraryCard_Number,Accession_Number, Date_of_issue,Date_of_return,Duration_of_issue,Fine_Charged from Transaction_Records";
            ResultSet rs = stmt.executeQuery(s);
            while (rs.next()) {
                String a11, b, c, d, e, f, g;
                a11 = rs.getString(1);
                b = rs.getString(2);
                c = rs.getString(3);
                d = rs.getString(4);
                e = rs.getString(5);
                f = rs.getString(6);
                g = rs.getString(7);

                m.addRow(new Object[]{a11, b, c, d, e, f, g});
            }
            if (m.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "No records to display");
            }
            stmt.close();
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int s = jTable1.getSelectedRow();
        s = s + 1;
        int count = 0, count1 = 0;
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/library", "root","mysql");
            Statement stmt = con.createStatement();
            Statement stmta = con.createStatement();
            String sa = "select * from disposed";
            String s1 = "select LibraryCard_Number,Accession_number,Date_of_issue from Transaction_records where Record_number='" + s + "';";
            ResultSet rs = stmt.executeQuery(s1);
            rs.first();
            ResultSet rs1 = stmta.executeQuery(sa);
            String l, ac;
            String x, y, z;
            x = rs.getString(1);
            y = rs.getString(2);
            while (rs1.next()) {
                l = rs1.getString(2);
                ac = rs1.getString(1);
                if (x.equals(l)) {
                    jTextField1.setText("");
                    jTextField2.setText("");
                    jTextField3.setText("");
                    jTextField4.setText("");
                    jTextField5.setText("");
                    JOptionPane.showMessageDialog(this, "The information has been disposed");

                    count1 = 1;
                    break;
                }

                if (y.equals(ac)) {
                    jTextField1.setText("");
                    jTextField2.setText("");
                    jTextField3.setText("");
                    jTextField4.setText("");
                    jTextField5.setText("");
                    JOptionPane.showMessageDialog(this, "The information has been disposed");

                    count1 = 1;
                    break;
                }
            }
            if (count1 == 0) {
                Statement stmt1 = con.createStatement();
                String s2 = "select LibraryCard_Number,Accession_number,Date_of_issue from Transaction_records where Record_number='" + s + "';";
                ResultSet rs3 = stmt1.executeQuery(s2);
                rs3.first();
                String x1 = rs3.getString(1);
                String y1 = rs3.getString(2);
                z = rs3.getString(3);
                String S = "select Name_of_issuer,Phone_numbers,Title from Registered_issuers,Book_information"
                        + " where LibraryCard_Number = '" + x1 + "' && Accession_Number = '" + y1 + "';";
                ResultSet Rs = stmt1.executeQuery(S);
                String a, b, c;
                Rs.first();
                a = Rs.getString(1);
                b = Rs.getString(2);
                c = Rs.getString(3);
                jTextField1.setText(a);
                jTextField2.setText(b);
                jTextField3.setText(c);
                jTextField4.setText(z);
                String ak = "select Record_Number from transaction_records where LibraryCard_Number='" + x + "';";
                ResultSet r1 = stmt1.executeQuery(ak);
                while (r1.next()) {
                    count++;
                }
                int k = count;
                if (k == 1) {
                    jTextField5.setText(Integer.toString(k) + " visit");
                } else {
                    jTextField5.setText(Integer.toString(k) + " visits");
                }

            }
            stmt.close();
            con.close();
        } catch (Exception e) {
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            String sk;
            sk = e.getMessage();
            if (sk.equals("Illegal operation on empty result set.")) {

                JOptionPane.showMessageDialog(this, "Book information has been disposed \n"
                        + "                            Or \n"
                        + "Issuer Information has been disposed");
            } else {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }

        }
// TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Records_archives.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Records_archives.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Records_archives.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Records_archives.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Records_archives().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
