/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Package1;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Samsung
 */
public class Registered_visitors extends javax.swing.JFrame {

   
    /**
     * Creates new form Registered_visitors
     */
    public Registered_visitors() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registered Visitors");

        jPanel1.setLayout(null);

        jButton1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton1.setText("View records");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(240, 110, 170, 70);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 50, 580, 10);

        jList1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 255)));
        jList1.setModel(new DefaultListModel());
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 70, 200, 430);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package1/home 1.png"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(430, 90, 110, 110);

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(230, 210, 80, 40);

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Phone Number :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(230, 250, 110, 60);

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Registration Date:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(230, 310, 120, 40);

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Address :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(230, 390, 90, 60);

        jTextField1.setEditable(false);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(340, 210, 200, 40);

        jTextField2.setEditable(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(340, 260, 200, 40);

        jTextField3.setEditable(false);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(340, 310, 200, 40);

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Number of visits :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(230, 340, 110, 80);

        jTextField4.setEditable(false);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(340, 360, 200, 40);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(340, 410, 200, 70);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(220, 70, 330, 430);

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText(" Library Card Numbers");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 10, 210, 50);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package1/666.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-190, -20, 920, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Front_Page k=new Front_Page();
k.playSound();
Front_Page ob=new Front_Page();
ob.setVisible(true);
this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
DefaultListModel m1=(DefaultListModel)jList1.getModel();
m1.clear();
    try{
    Class.forName("java.sql.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/library","root","mysql");
    Statement stmt=con.createStatement();
    Statement stmt1=con.createStatement();
    String s="select LibraryCard_Number from Registered_issuers";
    ResultSet rs=stmt1.executeQuery(s);
    ResultSet rs1=stmt.executeQuery(s);
    rs1.first();
    String k1=rs1.getString(1);
    while(rs.next())
    {
        String a=rs.getString(1);
       m1.addElement(a);
    }
    stmt.close();
    con.close();
    }
    catch(Exception e)
    {
        if(e.getMessage().equals("Illegal operation on empty result set."))
        {
            JOptionPane.showMessageDialog(this,"No records to display");
            int i=JOptionPane.showConfirmDialog(this,"Would someone like to register?","First Registration",JOptionPane.YES_NO_OPTION);
            if(i==0)
            {
                New_Registration_form ob= new New_Registration_form();
                ob.setVisible(true);
                this.dispose();
            }
            else
            {
                Registered_visitors ob=new Registered_visitors();
                ob.setVisible(true);
                this.dispose();
            }
            
        }
        else
        JOptionPane.showMessageDialog(this,e.getMessage());
    }// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
 int count=0;
 if(jList1.getSelectedValue()==null)
 {
     JOptionPane.showMessageDialog(this,"No Record Present");
 }
 else
 {
        try{
    Class.forName("java.sql.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/library","root","mysql");
    Statement stmt=con.createStatement();
    Object s1=jList1.getSelectedValue();
    String s2="select * from disposed;";
    ResultSet rs1=stmt.executeQuery(s2);
    int count1=0;
    while(rs1.next())
    {if(s1.equals(rs1.getString(2)))
    {
        count1=1;
        break;
    }
    }
    if(count1==1)
    {
        JOptionPane.showMessageDialog(this,"These records have been disposed");
        int i=JOptionPane.showConfirmDialog(this,"Wish to undispose?","Question",JOptionPane.YES_NO_OPTION);
        if(i==0)
        {
            Statement stmts=con.createStatement();
            String sa="delete from disposed where LibraryCard_number='"+s1+"';";
            stmts.executeUpdate(sa);
            JOptionPane.showMessageDialog(this,"Undisposed");
        }
    }
    else if(count1==0)
    {
    String s="select name_of_issuer,Phone_numbers,Date_Registration,address from Registered_issuers where LibraryCard_Number='"+s1+"';";
    ResultSet rs=stmt.executeQuery(s);
    while(rs.next())
    {
        String a=rs.getString(1);
        String b=rs.getString(2);
        String c=rs.getString(3);
        String d=rs.getString(4);
        
        jTextField1.setText(a);
        jTextField2.setText(b);
        jTextField3.setText(c);
        jTextArea1.setText(d);
        
        
    }
    String as="select Record_Number from Transaction_records where LibraryCard_Number='"+s1+"';";
    ResultSet r1=stmt.executeQuery(as);
    while(r1.next())
    {
        count++;
    }
    int k=count;
    if(count==1)
    jTextField4.setText(Integer.toString(k)+" visit");
    else
    jTextField4.setText(Integer.toString(k)+" visits");
}
    stmt.close();
    con.close();
        }
catch(Exception e)
{
    if(jList1.getSelectedValue()==null)
{
    JOptionPane.showMessageDialog(this,"No Library Card Number Selected");
}
    else
    {
    JOptionPane.showMessageDialog(this,e.getMessage());
}  
}
 }// TODO add your handling code here:
    }//GEN-LAST:event_jList1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registered_visitors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registered_visitors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registered_visitors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registered_visitors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registered_visitors().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
