/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Package1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Samsung
 */
public class Return_Book extends javax.swing.JFrame {

    /**
     * Creates new form Return_Book
     */
    public Return_Book() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Return Book");

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Library Card Number :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 90, 180, 60);

        jButton1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(150, 310, 160, 60);

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(220, 100, 190, 40);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package1/home 1.png"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(340, 320, 110, 110);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 72, 470, 20);

        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(220, 170, 190, 40);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(220, 240, 190, 40);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(150, 390, 160, 50);

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Return Books");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(140, 30, 210, 40);

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Book Number :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 160, 170, 60);

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Transaction Number :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 230, 170, 60);

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Duration :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 390, 90, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package1/376152628_249e3630c0_o.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-280, -90, 740, 590);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String s=jTextField3.getText();
        String sk=jTextField2.getText();
        int x=0;
        if(s.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Please enter a record number");
        }
        else if(sk.isEmpty())
        {
           JOptionPane.showMessageDialog(this,"Please enter the book number"); 
        }
        else if(s.isEmpty()==false)
        {
          try
{
    Class.forName("java.sql.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/library","root","mysql");
    Statement stmt=con.createStatement();
    String ssa="select date_of_return from transaction_records where record_number='"+s+"';";
    ResultSet rs=stmt.executeQuery(ssa);
    String a="";
    rs.first();
    a=rs.getString(1);
    
    if(a.isEmpty()==false)
    {
        JOptionPane.showMessageDialog(this,"This transaction has already been made");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField1.setText("");
        jTextField4.setText("");
        x=0;
    }
}
          catch(Exception e)
          {
             x=1;
          }
        }
        if(x==1)
        {
        try
{
    Class.forName("java.sql.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/library","root","mysql");
    Statement stmt=con.createStatement();
    Statement stmt1=con.createStatement();
    Statement stmt2=con.createStatement();
    String s2="select accession_number from transaction_records where record_number='"+s+"';";    
    String sql="update book_information set Stock_available = 1 where accession_number = '"+sk+"';";
    String s1="update Transaction_Records set Date_of_return = curdate() where Record_Number='"+s+"';";
      ResultSet rsk=stmt2.executeQuery(s2);
      rsk.first();
      int kount=0;
      String acc=rsk.getString(1);
      if(sk.equals(acc))
      {
          kount=1;
      }
      else
      {
          JOptionPane.showMessageDialog(this,"Incorrect Book Number");
          jTextField2.setText("");
          jTextField3.setText("");
          jTextField1.setText("");
          jTextField4.setText("");
          kount=0;
      }
      if(kount==1)
      {
    int i=stmt.executeUpdate(s1);
    int count=0;
    if(i==1)
    {
        JOptionPane.showMessageDialog(this,"Registration Complete");
        count=1;
    }
    else
    {
        JOptionPane.showMessageDialog(this,"Registration Failed");
        count=0;
    }
    if(count==1)
    {
    stmt1.executeUpdate(sql);
    }
    else
    {
        JOptionPane.showMessageDialog(this,"No such record exists");
        jTextField3.setText("");
        jTextField2.setText("");
        jTextField1.setText("");
        jTextField4.setText("");
    }

    String ss="select DateDiff(Date_of_return, Date_of_issue) from Transaction_Records where Record_Number='"+s+"';";
    ResultSet rs=stmt.executeQuery(ss);
    rs.first();
    String a=rs.getString(1);
    String a1=a+" days";
    jTextField4.setText(a+" days");
    String sa="update Transaction_Records set Duration_of_issue='"+a1+"' where Record_Number='"+s+"';";
    stmt.executeUpdate(sa);
    String f;
    if(Integer.parseInt(a)>15)
    {
        double fine;
        fine=5*(Integer.parseInt(a)-15);
        f=Double.toString(fine)+" Rs";
    }
    else
    {
        f="0 Rs";
    }
    String sm="update Transaction_records set Fine_Charged='"+f+"' where Record_Number='"+s+"';";
    stmt.executeUpdate(sm);
    stmt.close();
    con.close();
}
}
catch(Exception e)
{
    
    String a=e.getMessage();
    if(a.equals("Illegal operation on empty result set."))
    {
        JOptionPane.showMessageDialog(this,"No such record exists");
        jTextField3.setText("");
        jTextField2.setText("");
        jTextField1.setText("");
        jTextField4.setText("");
    }
    else{
        JOptionPane.showMessageDialog(this,e.getMessage());
    }
    
}
        }              // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Front_Page k=new Front_Page();
k.playSound();
Front_Page ob= new Front_Page();
ob.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
String s=jTextField2.getText();
  try{
    Class.forName("java.sql.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/library","root","mysql");
    Statement stmt=con.createStatement();
    String s1="select * from disposed;";
    ResultSet rs1=stmt.executeQuery(s1);
    int count=0;
    while(rs1.next())
    {if(s.equals(rs1.getString(1)))
    {
        count=1;
        break;
    }
    }
    if(count==1)
    {
        JOptionPane.showMessageDialog(this,"The Book records have been disposed");
        jTextField2.setText("");
        jTextField1.setText("");
    }
    stmt.close();
    con.close();
  }
catch(Exception e)
{
JOptionPane.showMessageDialog(this,e.getMessage());
}// TODO add your handling code here:
    }//GEN-LAST:event_jTextField2FocusLost

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
String s=jTextField1.getText();

  try{
    Class.forName("java.sql.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/library","root","mysql");
    Statement stmt=con.createStatement();
    String s1="select * from disposed;";
    ResultSet rs1=stmt.executeQuery(s1);
    int count=0;
    while(rs1.next())
    {if(s.equals(rs1.getString(2)))
    {
        count=1;
        break;
    }
    }
    if(count==1)
    {
        JOptionPane.showMessageDialog(this,"The Issuer records have been disposed");
        jTextField1.setText("");
    }
    stmt.close();
    con.close();
  }
catch(Exception e)
{
JOptionPane.showMessageDialog(this,e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Return_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Return_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Return_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Return_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Return_Book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
