/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Package1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Samsung
 */
public class View_books extends javax.swing.JFrame {

    /**
     * Creates new form View_books
     */
    public View_books() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registered Books");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(null);

        jButton1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton1.setText("View Records");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(230, 150, 190, 50);

        jList1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 51)));
        jList1.setModel(new DefaultListModel());
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 70, 200, 430);

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("List of books");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 210, 80);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package1/home 1.png"))); // NOI18N
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(430, 90, 110, 110);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Title :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(230, 230, 110, 40);

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Author :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(230, 280, 120, 40);

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Genre :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(230, 320, 90, 60);

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Price :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(230, 360, 60, 80);

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Stock Available :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(230, 420, 100, 70);

        jTextField1.setEditable(false);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(330, 230, 210, 40);

        jTextField2.setEditable(false);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(330, 280, 210, 40);

        jTextField3.setEditable(false);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(330, 330, 210, 40);

        jTextField4.setEditable(false);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(330, 380, 210, 40);

        jTextField5.setEditable(false);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(330, 430, 210, 40);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 50, 560, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox1MousePressed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(230, 100, 190, 40);

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Pick Genre :               (Optional)");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(230, 74, 190, 30);
        jPanel1.add(jLabel8);
        jLabel8.setBounds(220, 70, 330, 430);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package1/122.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-50, -40, 1090, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
Front_Page k=new Front_Page();
k.playSound();
Front_Page ob= new Front_Page();
ob.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
jTextField1.setText("");
       jTextField2.setText("");
       jTextField3.setText("");
       jTextField4.setText("");
       jTextField5.setText("");
        DefaultListModel m=(DefaultListModel)(jList1.getModel());
m.clear();
int count=0;
if(jComboBox1.getSelectedItem()==" ")
{
    try{
    Class.forName("java.sql.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/library","root","mysql");
    Statement stmt=con.createStatement();
    Statement stmt1=con.createStatement();
    String s="select accession_number from book_information order by Accession_number asc;";
    ResultSet rs=stmt.executeQuery(s);
    ResultSet rs1=stmt1.executeQuery(s);
    rs1.first();
    String k=rs1.getString(1);
    while(rs.next())
    {
       String a=rs.getString(1);
       m.addElement(a);
    }
    stmt.close();
    con.close();
    }
    catch(Exception e)
    {
        if(e.getMessage().equals("Illegal operation on empty result set."))
        {
            JOptionPane.showMessageDialog(this,"No records to display");
            int i=JOptionPane.showConfirmDialog(this,"Wish to add a book to your Library?","First Registration",JOptionPane.YES_NO_OPTION);
            if(i==0)
            {
                Add_new_book ob= new Add_new_book();
                ob.setVisible(true);
                this.dispose();
            }
            else
            {
                View_books ob=new View_books();
                ob.setVisible(true);
                this.dispose();
            }
        }
            else
            {
        JOptionPane.showMessageDialog(this,e.getMessage());
                    }
    
    }
}
else{
    Object ex=jComboBox1.getSelectedItem();
    try{
    Class.forName("java.sql.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/library","root","mysql");
    Statement stmt=con.createStatement();
    Statement stmt1=con.createStatement();
    String s="select accession_number from book_information where genre='"+ex+"';";
    ResultSet rs=stmt.executeQuery(s);
    ResultSet rs1=stmt1.executeQuery(s);
    rs1.first();
    String k=rs1.getString(1);
    while(rs.next())
    {
       String a=rs.getString(1);
       m.addElement(a);
    }
    stmt.close();
    con.close();
    }
    catch(Exception e)
    {
        if(e.getMessage().equals("Illegal operation on empty result set."))
        {
            JOptionPane.showMessageDialog(this,"No records to display");
            int i=JOptionPane.showConfirmDialog(this,"Wish to add a book to your Library?","First Registration",JOptionPane.YES_NO_OPTION);
            if(i==0)
            {
                Add_new_book ob= new Add_new_book();
                ob.setVisible(true);
                this.dispose();
            }
            else
            {
                View_books ob=new View_books();
                ob.setVisible(true);
                this.dispose();
            }
        }
            else
        JOptionPane.showMessageDialog(this,e.getMessage());
    }
}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
 
        try{
    Class.forName("java.sql.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/library","root","mysql");
    Statement stmt=con.createStatement();
    Object a1=jList1.getSelectedValue();
    String s1="select * from disposed;";
    ResultSet rs1=stmt.executeQuery(s1);
    int count=0;
    while(rs1.next())
    {if(a1.equals(rs1.getString(1)))
    {
        count=1;
        break;
    }
    }
    if(count==1)
    {
        JOptionPane.showMessageDialog(this,"These records have been disposed");
        int i=JOptionPane.showConfirmDialog(this,"Wish to undispose?","Question",JOptionPane.YES_NO_OPTION);
        if(i==0)
        {
            Statement stmts=con.createStatement();
            String sa="delete from disposed where accession_number='"+a1+"';";
            stmts.executeUpdate(sa);
            JOptionPane.showMessageDialog(this,"Undisposed");
        }
    }
    else if(count==0)
    {String s="select Title,Author,Genre,Price,Stock_Available from book_information where accession_number ='"+a1+"';";
    ResultSet rs=stmt.executeQuery(s);
    while(rs.next())
    {
       String a=rs.getString(1);
       String b= rs.getString(2);
       String c= rs.getString(3);
       String d=rs.getString(4);
       String e=rs.getString(5);
       jTextField1.setText(a);
       jTextField2.setText(b);
       jTextField3.setText(c);
       jTextField4.setText(d);
       jTextField5.setText(e);
    }
    }
    stmt.close();
    con.close();
    }
    catch(Exception e)
    {
        if(jList1.getSelectedValue()==null)
{
    JOptionPane.showMessageDialog(this,"No book Selected");
}
    else
    {
        JOptionPane.showMessageDialog(this,e.getMessage());
    }     
    }// TODO add your handling code here:
    }//GEN-LAST:event_jList1MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
DefaultComboBoxModel m1=(DefaultComboBoxModel)(jComboBox1.getModel());
try{
    Class.forName("java.sql.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/library","root","mysql");
    Statement stmt=con.createStatement();
    String s="select distinct genre from book_information;";
    ResultSet rs=stmt.executeQuery(s);
    while(rs.next())
    {
       String a=rs.getString(1);
       m1.addElement(a);
    }
    stmt.close();
    con.close();
    }
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(this,e.getMessage());
    }        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jComboBox1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MousePressed
DefaultListModel m1=(DefaultListModel)(jList1.getModel());
m1.clear();// TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_books().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
